### ISSUE TITLE
Reduce the amount of code copied from Tailwind itself

### ISSUE THREAD

**Issue by nanorepublica** [softwarecrafts/tailwind-component-classes#12]
* Identify parts of the code that have been copied, that could be potential PR worthy for the main code base?
* Fork Tailwind and make changes
* Create PR

**Comment by jgornick** [comment]
Does this mean that with a configuration that aliases `border-purple-default` to `border-purple-900`:

```javascript
module.exports = {
  plugins: [require('tailwind-component-classes')],
  utilities: {
    'border-purple-default': 'border-purple-900',
  },
}
```

... the output would look like:

```css
.border-purple-900,
.border-purple-default {
  --tw-border-opacity: 1;
  border-color: rgb(88 28 135 / var(--tw-border-opacity))
}
```

... instead of:

```css
.border-purple-900 {
  --tw-border-opacity: 1;
  border-color: rgb(88 28 135 / var(--tw-border-opacity))
}

.border-purple-default {
  --tw-border-opacity: 1;
  border-color: rgb(88 28 135 / var(--tw-border-opacity))
}
```
